package knowledge

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Scanner walks a repository directory and produces a TreeNode hierarchy.
type Scanner struct {
	ignoreRules []ignoreRule
	mode        ScanMode
}

type ignoreRule struct {
	pattern  string
	negate   bool
	dirOnly  bool
	anchored bool // pattern contains '/' (anchored to gitignore location)
}

// -----------------------------------------------------------------------
// Default‐ignore directories: always skipped in both smart and deep modes
// because they never contain useful source code (VCS internals, OS junk).
// -----------------------------------------------------------------------
var alwaysIgnoreDirs = map[string]bool{
	".git":      true,
	".DS_Store": true,
	".hg":       true,
	".svn":      true,
}

// -----------------------------------------------------------------------
// Smart-mode directory ignore list.
// These are dependency / cache / build-output directories that package
// managers and build tools create automatically.
// -----------------------------------------------------------------------
var smartIgnoreDirs = map[string]bool{
	// JS/Node
	"node_modules":     true,
	"bower_components": true,
	".yarn":            true,
	".pnp":             true,

	// Python
	"__pycache__":   true,
	".venv":         true,
	"venv":          true,
	"env":           true,
	".tox":          true,
	".mypy_cache":   true,
	".pytest_cache": true,
	".ruff_cache":   true,
	"site-packages": true,
	".eggs":         true,
	"dist-info":     true,

	// Go
	"vendor": true,

	// Rust
	"target": true,

	// Java / Kotlin / Gradle / Maven
	".gradle": true,
	".mvn":    true,

	// Ruby
	".bundle": true,

	// .NET
	"obj": true,

	// Dart / Flutter
	".dart_tool": true,
	".pub-cache": true,

	// Build outputs
	"dist":    true,
	"build":   true,
	"out":     true,
	".next":   true,
	".nuxt":   true,
	".output": true,
	"_build":  true,

	// IDE / editor
	".idea":   true,
	".vscode": true,
	".vs":     true,

	// Infra / CI caches
	".terraform":    true,
	".cache":        true,
	".parcel-cache": true,
	"coverage":      true,
	"htmlcov":       true,
}

// -----------------------------------------------------------------------
// Known path segments that indicate third-party / vendored code even when
// they sit inside otherwise-allowed directory trees.  Matched against each
// segment of the relative path.
// -----------------------------------------------------------------------
var smartIgnorePathSegments = map[string]bool{
	"site-packages":  true,
	"dist-info":      true,
	"egg-info":       true,
	"__pypackages__": true,
}

// -----------------------------------------------------------------------
// Lock files and machine-generated metadata that never contain user logic.
// -----------------------------------------------------------------------
var lockAndMetaFiles = map[string]bool{
	"package-lock.json":   true,
	"yarn.lock":           true,
	"pnpm-lock.yaml":      true,
	"Cargo.lock":          true,
	"poetry.lock":         true,
	"Gemfile.lock":        true,
	"go.sum":              true,
	"Pipfile.lock":        true,
	"composer.lock":       true,
	"pubspec.lock":        true,
	"flake.lock":          true,
	"pnpm-workspace.yaml": true,
	"RECORD":              true,
	"METADATA":            true,
	"WHEEL":               true,
	"top_level.txt":       true,
	"INSTALLER":           true,
	"entry_points.txt":    true,
	"direct_url.json":     true,
}

// -----------------------------------------------------------------------
// File suffixes that indicate auto-generated or non-human-written code.
// -----------------------------------------------------------------------
var generatedSuffixes = []string{
	".pb.go",        // protobuf-go
	".pb.gw.go",     // grpc-gateway
	"_generated.go", // k8s, code-gen
	".gen.go",
	"_gen.go",
	"_string.go", // stringer
	".generated.ts",
	".generated.js",
	".d.ts", // TypeScript declarations
	".map",  // source maps
	".min.js",
	".min.css",
	".chunk.js",
	".chunk.css",
	".bundle.js",
	".bundle.css",
}

// -----------------------------------------------------------------------
// Certificate, key, and data files that are never source code.
// -----------------------------------------------------------------------
var nonCodeExtensions = map[string]bool{
	".pem":  true,
	".crt":  true,
	".key":  true,
	".cer":  true,
	".der":  true,
	".p12":  true,
	".pfx":  true,
	".csv":  true,
	".tsv":  true,
	".log":  true,
	".bak":  true,
	".orig": true,
	".swp":  true,
	".swo":  true,
	".tmp":  true,
	".lock": true,
}

// -----------------------------------------------------------------------
// First-line markers that indicate a file was auto-generated.
// We read up to the first 5 lines looking for any of these (case-insensitive).
// -----------------------------------------------------------------------
var generatedMarkers = []string{
	"do not edit",
	"auto-generated",
	"autogenerated",
	"@generated",
	"generated by",
	"code generated",
	"this file is generated",
	"automatically generated",
	"machine generated",
}

// binaryExtensions are file extensions treated as binary and skipped.
var binaryExtensions = map[string]bool{
	".exe": true, ".dll": true, ".so": true, ".dylib": true, ".a": true, ".o": true,
	".bin": true, ".dat": true, ".db": true, ".sqlite": true, ".sqlite3": true,
	".png": true, ".jpg": true, ".jpeg": true, ".gif": true, ".bmp": true, ".ico": true,
	".webp": true, ".svg": true, ".tiff": true, ".tif": true,
	".mp3": true, ".mp4": true, ".avi": true, ".mov": true, ".mkv": true, ".wav": true,
	".flac": true, ".ogg": true, ".webm": true,
	".zip": true, ".tar": true, ".gz": true, ".bz2": true, ".xz": true, ".7z": true,
	".rar": true, ".jar": true, ".war": true,
	".pdf": true, ".doc": true, ".docx": true, ".xls": true, ".xlsx": true, ".pptx": true,
	".woff": true, ".woff2": true, ".ttf": true, ".otf": true, ".eot": true,
	".pyc": true, ".pyo": true, ".class": true,
	".wasm": true, ".min.js": true, ".min.css": true,
}

// extensionToLanguage maps common file extensions to language names.
var extensionToLanguage = map[string]string{
	".go":     "go",
	".py":     "python",
	".js":     "javascript",
	".jsx":    "javascript",
	".ts":     "typescript",
	".tsx":    "typescript",
	".java":   "java",
	".kt":     "kotlin",
	".rs":     "rust",
	".c":      "c",
	".cpp":    "cpp",
	".cc":     "cpp",
	".h":      "c",
	".hpp":    "cpp",
	".cs":     "csharp",
	".rb":     "ruby",
	".php":    "php",
	".swift":  "swift",
	".m":      "objectivec",
	".scala":  "scala",
	".r":      "r",
	".R":      "r",
	".lua":    "lua",
	".pl":     "perl",
	".sh":     "shell",
	".bash":   "shell",
	".zsh":    "shell",
	".fish":   "shell",
	".ps1":    "powershell",
	".sql":    "sql",
	".html":   "html",
	".htm":    "html",
	".css":    "css",
	".scss":   "scss",
	".less":   "less",
	".json":   "json",
	".yaml":   "yaml",
	".yml":    "yaml",
	".toml":   "toml",
	".xml":    "xml",
	".md":     "markdown",
	".rst":    "restructuredtext",
	".proto":  "protobuf",
	".tf":     "terraform",
	".vue":    "vue",
	".svelte": "svelte",
	".dart":   "dart",
	".ex":     "elixir",
	".exs":    "elixir",
	".erl":    "erlang",
	".hs":     "haskell",
	".clj":    "clojure",
	".ml":     "ocaml",
	".zig":    "zig",
	".nim":    "nim",
	".v":      "v",
	".sol":    "solidity",
}

// ScanResult holds the output of a repository scan.
type ScanResult struct {
	Tree        []TreeNode
	FileCount   int
	TotalBytes  int64
	SkippedDirs int // directories skipped by smart filtering
	SkippedGen  int // files skipped as auto-generated
}

// ScanRepo walks the repository at rootPath and returns a flat list of file TreeNodes.
// It respects the given ScanMode: ScanModeSmart filters aggressively; ScanModeDeep keeps everything.
func ScanRepo(rootPath string, mode ScanMode) (*ScanResult, error) {
	if mode == "" {
		mode = ScanModeSmart
	}
	absRoot, err := filepath.Abs(rootPath)
	if err != nil {
		return nil, fmt.Errorf("resolve root: %w", err)
	}

	info, err := os.Stat(absRoot)
	if err != nil {
		return nil, fmt.Errorf("stat root: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", absRoot)
	}

	s := &Scanner{mode: mode}
	s.loadGitignore(absRoot)

	var files []TreeNode
	var totalBytes int64
	var skippedDirs, skippedGen int

	err = filepath.WalkDir(absRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil // skip unreadable entries
		}

		rel, err := filepath.Rel(absRoot, path)
		if err != nil {
			return nil
		}
		if rel == "." {
			return nil
		}

		name := d.Name()

		// ---- Directory filtering ----
		if d.IsDir() {
			// Always skip VCS internals and OS junk
			if alwaysIgnoreDirs[name] {
				skippedDirs++
				return filepath.SkipDir
			}

			// Smart mode: skip dependency, cache, build, IDE dirs
			if mode == ScanModeSmart {
				if smartIgnoreDirs[name] {
					skippedDirs++
					return filepath.SkipDir
				}
				// Check path segments for deep vendor paths
				for _, seg := range strings.Split(rel, string(filepath.Separator)) {
					if smartIgnorePathSegments[seg] {
						skippedDirs++
						return filepath.SkipDir
					}
				}
			}
		}

		// Check gitignore rules
		if s.isIgnored(rel, d.IsDir()) {
			if d.IsDir() {
				skippedDirs++
				return filepath.SkipDir
			}
			return nil
		}

		if d.IsDir() {
			return nil // don't add dirs to the flat list
		}

		// ---- File filtering ----

		// Skip binary files by extension (always, in both modes)
		ext := strings.ToLower(filepath.Ext(name))
		if binaryExtensions[ext] {
			return nil
		}

		// Smart mode file filtering
		if mode == ScanModeSmart {
			// Lock / metadata files
			if lockAndMetaFiles[name] {
				return nil
			}

			// Non-code extensions (.pem, .crt, .log, .bak, etc.)
			if nonCodeExtensions[ext] {
				return nil
			}

			// Generated file suffixes (.pb.go, .min.js, .d.ts, .map, etc.)
			lowerName := strings.ToLower(name)
			for _, suffix := range generatedSuffixes {
				if strings.HasSuffix(lowerName, suffix) {
					skippedGen++
					return nil
				}
			}
		}

		// Skip very large files (>1MB)
		fi, err := d.Info()
		if err != nil {
			return nil
		}
		if fi.Size() > 1<<20 {
			return nil
		}

		// Quick binary check: read first 512 bytes looking for null bytes
		if isBinaryFile(path) {
			return nil
		}

		// Smart mode: check first few lines for "auto-generated" markers
		if mode == ScanModeSmart && hasGeneratedMarker(path) {
			skippedGen++
			return nil
		}

		lang := extensionToLanguage[ext]
		tokens := estimateTokens(fi.Size())

		files = append(files, TreeNode{
			Path:     rel,
			Name:     name,
			Type:     "file",
			Size:     fi.Size(),
			Hash:     fileHash(path),
			Language: lang,
			Tokens:   tokens,
		})
		totalBytes += fi.Size()

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk repo: %w", err)
	}

	return &ScanResult{
		Tree:        files,
		FileCount:   len(files),
		TotalBytes:  totalBytes,
		SkippedDirs: skippedDirs,
		SkippedGen:  skippedGen,
	}, nil
}

// hasGeneratedMarker reads the first few lines of a file and returns true
// if any of them contain a well-known auto-generation marker.
func hasGeneratedMarker(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		lower := strings.ToLower(scanner.Text())
		for _, marker := range generatedMarkers {
			if strings.Contains(lower, marker) {
				return true
			}
		}
	}
	return false
}

func (s *Scanner) loadGitignore(rootPath string) {
	gitignorePath := filepath.Join(rootPath, ".gitignore")
	f, err := os.Open(gitignorePath)
	if err != nil {
		return
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		rule := ignoreRule{}
		if strings.HasPrefix(line, "!") {
			rule.negate = true
			line = line[1:]
		}
		if strings.HasSuffix(line, "/") {
			rule.dirOnly = true
			line = strings.TrimSuffix(line, "/")
		}
		if strings.Contains(line, "/") {
			rule.anchored = true
		}
		rule.pattern = line
		s.ignoreRules = append(s.ignoreRules, rule)
	}
}

func (s *Scanner) isIgnored(relPath string, isDir bool) bool {
	ignored := false
	for _, rule := range s.ignoreRules {
		if rule.dirOnly && !isDir {
			continue
		}

		var matched bool
		if rule.anchored {
			matched, _ = filepath.Match(rule.pattern, relPath)
		} else {
			// Match against the basename
			base := filepath.Base(relPath)
			matched, _ = filepath.Match(rule.pattern, base)
			if !matched {
				// Also try matching the full relative path
				matched, _ = filepath.Match(rule.pattern, relPath)
			}
		}

		if matched {
			ignored = !rule.negate
		}
	}
	return ignored
}

func isBinaryFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return true
	}
	defer f.Close()

	buf := make([]byte, 512)
	n, err := f.Read(buf)
	if n == 0 {
		return false
	}
	for _, b := range buf[:n] {
		if b == 0 {
			return true
		}
	}
	return false
}

func fileHash(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	h := sha256.Sum256(data)
	return fmt.Sprintf("%x", h[:16])
}

// estimateTokens gives a rough token count for a file based on byte size.
// Approximation: ~4 bytes per token for code.
func estimateTokens(sizeBytes int64) int {
	return int(sizeBytes / 4)
}
